# To see all cops, see:
# http://rubocop.readthedocs.io/en/latest/cops/
# For configuration details and how to locally disable cops, see:
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/assets/**/*'
    - '**/uploads/**/*'
    - '**/javascript/**/*'
    - '**/views/**/*'
    - '**/bin/**/*'
    - '**/coverage/**/*'
    - '**/db/**/schema.rb'
    - '**/log/**/*'
    - '**/public/**/*'
    - '**/storage/**/*'
    - '**/script/**/*'
    - '**/vendor/**/*'
    - '**/tmp/**/*'
    - '**/node_modules/**/*'
  ExtraDetails: true
  NewCops: enable

# Bundler
Bundler/OrderedGems:
  Enabled: true

# Layout
Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/EndAlignment:
  AutoCorrect: true
  Enabled: true
  EnforcedStyleAlignWith: keyword

Layout/ExtraSpacing:
  AllowForAlignment: false
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/LineLength:
  Max: 300
  Exclude:
    - '**/db/**/*'

# Lint
Lint/EmptyBlock:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'

Lint/InheritException:
  Enabled: true
  EnforcedStyle: standard_error

Lint/MultipleComparison:
  AutoCorrect: false
  Details: 'Use y.between?(x,z) instead of x < y < z'
  Enabled: true

Lint/Void:
  CheckForMethodsWithNoSideEffects: true
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
  - '**/spec/**/*'

# Metrics
Metrics/ParameterLists:
  Enabled: true
  Exclude:
  - '**/controllers/*'

Metrics/AbcSize:
  Max: 300

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 80
  Exclude:
    - '**/db/**/*'

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 50

Metrics/ModuleLength:
  Enabled: true
  Exclude:
  - '**/spec/**/*'

# Naming
Naming/HeredocDelimiterNaming:
  Enabled: true
  Exclude:
    - '**/config/**/*'

Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - is_using_in
    - has_related_questions
  Enabled: true
  Exclude:
    - '**/app/serializers/**/*'
    - '**/spec/**/*'
  ForbiddenPrefixes:
    - is_

Naming/VariableNumber:
  Enabled: true
  Exclude:
    - '**/spec/**/*'
    - '**/db/**/*'

Naming/FileName:
  Enabled: true
  Exclude:
    - '**/initializers/rswag-ui.rb'

# Performance
Performance/CollectionLiteralInLoop:
  Exclude:
    - '**/db/seeds.rb'

Performance/StartWith:
  AutoCorrect: true
  Enabled: true

Performance/TimesMap:
  AutoCorrect: true
  Enabled: true

#
RSpec/FactoryBot/AttributeDefinedStatically:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 10

RSpec/ExampleLength:
  Enabled: true
  Max: 50
  Exclude:
    - '**/spec/requests/**/*.rb'

RSpec/EmptyExampleGroup:
  Enabled: true
  Severity: warning
  Exclude:
    - '**/spec/requests/**/*.rb'

RSpec/VariableName:
  Enabled: true
  Exclude:
    - '**/spec/requests/**/*.rb'
    - '**/spec/support/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 20

RSpec/ScatteredSetup:
  Enabled: true
  Exclude:
    - '**/spec/requests/**/*.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Exclude:
  - '**/spec/**/*'

RSpec/LetSetup:
  Exclude:
  - '**/spec/**/*'

RSpec/NamedSubject:
  Enabled: true
  Severity: warning

RSpec/ImplicitSubject:
  Exclude:
  - '**/spec/requests/**/*.rb'

RSpec/FilePath:
  Enabled: true
  Exclude:
    - '**/spec/lib/**/*.rb'

# Rails
Rails/OutputSafety:
  Enabled: true
  Severity: error

Rails/I18nLocaleTexts:
  Enabled: true
  Severity: error

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true
  Whitelist:
    - find_by_sql
    - find_by_english_name
    - find_by_email

Rails/FilePath:
  Enabled: false

Rails/FindBy:
  Enabled: true
  Include:
    - '**/*.rb'

Rails/FindEach:
  Enabled: true
  Include:
    - '**/*.rb'

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/Output:
  Enabled: true
  Exclude:
    - '**/config/puma.rb'
    - '**/initializers/*.rb'
    - '**/seeds.rb'

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

# Style
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/IfUnlessModifier:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Severity: error
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/ModuleFunction:
  Enabled: true
  Severity: warning

Style/ReturnNil:
  Description: 'Use return instead of return nil.'
  Enabled: true
  EnforcedStyle: return
  SupportedStyles:
    - return
    - return_nil

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - '**/serializers/**/*'

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  StyleGuide: '#map-find-select-reduce-include-size'
  Enabled: true
  Safe: false
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'
    member?: 'include?'

Style/FormatStringToken:
  Enabled: false

Style/EvalWithLocation:
  Enabled: true
  Exclude:
    - '**/initializers/**/*'

# Security
Security/MarshalLoad:
  Enabled: true
